export const SUBMIT_CONTACT="SUBMIT_CONTACT";
export const GET_CONTACT="GET_CONTACT";
export const VIEW_CONTACT="VIEW_CONTACT";
export const REMOVE_CONTACT="REMOVE_CONTACT";
export const EDIT_CONTACT="EDIT_CONTACT";